/**
 * The release version of this package.
 *
 * Generated by `scripts/version.ts` from `package.json`, which is the single
 * source of truth for the release version. Do not edit by hand. JSR publishes
 * the TypeScript sources, so this module is what makes the source-distributed
 * CLI report the same version as the packaged one.
 */
export const version = "0.6.0";
