/**
 * Keeps every release version of this package derived from `package.json`, which
 * is the single source of truth. npm ships `dist/cli.js` with the version inlined
 * by the build, while JSR ships the TypeScript sources, so `src/version.ts` is a
 * generated, checked-in module the source channel reads.
 *
 * Usage:
 *   node ./scripts/version.ts            rewrite generated metadata from package.json
 *   node ./scripts/version.ts --check    fail when any metadata disagrees
 *   node ./scripts/version.ts --if-present  rewrite only metadata that exists
 *
 * `--check` is the release gate. It only reads, so nothing repairs drift before
 * the gate observes it.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import process from "node:process";

const packageRoot = resolve(import.meta.dirname, "..");

const manifestPath = resolve(packageRoot, "package.json");
const jsrManifestPath = resolve(packageRoot, "jsr.json");
const versionModulePath = resolve(packageRoot, "src/version.ts");
const packageChangelogPath = resolve(packageRoot, "CHANGELOG.md");
const workspaceChangelogPath = resolve(packageRoot, "../../CHANGELOG.md");

const versionModuleHeader = `/**
 * The release version of this package.
 *
 * Generated by \`scripts/version.ts\` from \`package.json\`. Do not edit by hand.
 */
`;

const isRecord = (value: unknown): value is Record<string, unknown> =>
	typeof value === "object" && value !== null;

function check(condition: unknown, message: string): asserts condition {
	if (!condition) {
		throw new Error(message);
	}
}

const readSource = (path: string): string => {
	try {
		return readFileSync(path, "utf8");
	} catch (error) {
		throw new Error(`${path} could not be read: ${(error as Error).message}`);
	}
};

/** Reads a file that a first sync is expected to create. */
const readSourceOrDefault = (path: string): string => {
	try {
		return readFileSync(path, "utf8");
	} catch {
		return "";
	}
};

/** Reads a file only when it is present. */
const readSourceOrUndefined = (path: string): string | undefined => {
	try {
		return readFileSync(path, "utf8");
	} catch {
		return undefined;
	}
};

const readJson = (path: string): Record<string, unknown> => {
	const parsed: unknown = JSON.parse(readSource(path));
	check(isRecord(parsed), `${path} must contain a JSON object`);

	return parsed;
};

const readVersion = (manifest: Record<string, unknown>, description: string): string => {
	const { version } = manifest;
	check(
		typeof version === "string" && /^\d+\.\d+\.\d+/.test(version),
		`${description} must declare a semantic "version"`,
	);

	return version;
};

/** `package.json` is the single source of truth for the release version. */
const readPackageVersion = (): string =>
	readVersion(readJson(manifestPath), "package.json");

/** The generated module, in the exact shape this script writes. */
const renderVersionModule = (version: string): string =>
	`${versionModuleHeader}export const version = ${JSON.stringify(version)};\n`;

const readGeneratedVersion = (source: string): string | undefined =>
	source.match(/export const version = "([^"]+)";/)?.[1];

/** Rewrites the version in place so the file keeps its repository formatting. */
const rewriteVersionField = (
	path: string,
	description: string,
	version: string,
): void => {
	const source = readSource(path);
	const pattern = /("version"\s*:\s*")[^"]*(")/;
	check(pattern.test(source), `${path} has no "version" field to rewrite`);

	const updated = source.replace(pattern, `$1${version}$2`);
	JSON.parse(updated);
	writeFileSync(path, updated);

	const previous = source.match(pattern)?.[0];
	if (previous !== `"version": "${version}"`) {
		console.log(`${description}: version rewritten to ${version}`);
	}
};

/** Confirms the changelog answers for the version being released. */
const verifyChangelog = (version: string): void => {
	const heading = new RegExp(`^##\\s+${version.replaceAll(".", "\\.")}\\s*$`, "m");

	// This package ships its changelog in the published tarball.
	check(
		heading.test(readSource(packageChangelogPath)),
		`packages/cssforge/CHANGELOG.md has no "## ${version}" entry, so the release version and the changelog disagree`,
	);

	// The root changelog is optional for a release that only bumps this package.
	const workspaceChangelog = readSourceOrUndefined(workspaceChangelogPath);
	if (workspaceChangelog !== undefined) {
		check(
			heading.test(workspaceChangelog),
			`the root CHANGELOG.md has no "## ${version}" entry, so the release version and the changelog disagree`,
		);
	}
};

const main = (): void => {
	const checkOnly = process.argv.includes("--check");
	const version = readPackageVersion();

	if (checkOnly) {
		const discrepancies: string[] = [];

		const jsrVersion = readVersion(readJson(jsrManifestPath), "jsr.json");
		if (jsrVersion !== version) {
			discrepancies.push(`jsr.json declares ${jsrVersion}`);
		}

		const generated = readGeneratedVersion(readSourceOrDefault(versionModulePath));
		if (generated !== version) {
			discrepancies.push(`src/version.ts declares ${generated ?? "no version"}`);
		}

		if (discrepancies.length > 0) {
			throw new Error(
				`release metadata disagrees with package.json@${version}: ${discrepancies.join(", ")}. ` +
					"Run `moon run cssforge:version-sync` and commit the result.",
			);
		}

		verifyChangelog(version);
		console.log(`version metadata is consistent at ${version}`);

		return;
	}

	const onlyWhenPresent = process.argv.includes("--if-present");

	if (!onlyWhenPresent || readSourceOrUndefined(jsrManifestPath) !== undefined) {
		rewriteVersionField(jsrManifestPath, "jsr.json", version);
	}

	if (!onlyWhenPresent || readSourceOrUndefined(versionModulePath) !== undefined) {
		if (readGeneratedVersion(readSourceOrDefault(versionModulePath)) !== version) {
			writeFileSync(versionModulePath, renderVersionModule(version));
			console.log(`src/version.ts: version written as ${version}`);
		}
	}

	console.log(`version source: package.json@${version}`);
};

main();
